const uint8_t KC_A     = 0x04;    //  A
const uint8_t KC_B     = 0x05;    //  B
const uint8_t KC_C     = 0x06;    //  C
const uint8_t KC_D     = 0x07;    //  D
const uint8_t KC_E     = 0x08;    //  E
const uint8_t KC_F     = 0x09;    //  F
const uint8_t KC_G     = 0x0A;    //  G
const uint8_t KC_H     = 0x0B;    //  H
const uint8_t KC_I     = 0x0C;    //  I
const uint8_t KC_J     = 0x0D;    //  J  
const uint8_t KC_K     = 0x0E;    //  K  
const uint8_t KC_L     = 0x0F;    //  L  
const uint8_t KC_M     = 0x10;    //  M  
const uint8_t KC_N     = 0x11;    //  N  
const uint8_t KC_O     = 0x12;    //  O  
const uint8_t KC_P     = 0x13;    //  P  
const uint8_t KC_Q     = 0x14;    //  Q  
const uint8_t KC_R     = 0x15;    //  R  
const uint8_t KC_S     = 0x16;    //  S  
const uint8_t KC_T     = 0x17;    //  T  
const uint8_t KC_U     = 0x18;    //  U  
const uint8_t KC_V     = 0x19;    //  V  
const uint8_t KC_W     = 0x1A;    //  W  
const uint8_t KC_X     = 0x1B;    //  X  
const uint8_t KC_Y     = 0x1C;    //  Y  
const uint8_t KC_Z     = 0x1D;    //  Z   

const uint8_t KC_1     = 0x1E;    //  1 
const uint8_t KC_2     = 0x1F;    //  2  
const uint8_t KC_3     = 0x20;    //  3  
const uint8_t KC_4     = 0x21;    //  4  
const uint8_t KC_5     = 0x22;    //  5  
const uint8_t KC_6     = 0x23;    //  6  
const uint8_t KC_7     = 0x24;    //  7  
const uint8_t KC_8     = 0x25;    //  8  
const uint8_t KC_9     = 0x26;    //  9  
const uint8_t KC_0     = 0x27;    //  0  

const uint8_t KC_JSW   = 0x00;    //  半角/全角
const uint8_t KC_HYPN  = 0x2D;    //  -
const uint8_t KC_HAT   = 0x2E;    //  ^
const uint8_t KC_VBAR  = 0x00;    //  |
const uint8_t KC_TAB   = 0x2B;    //  Tab
const uint8_t KC_ATMK  = 0x00;    //  @
const uint8_t KC_LSQB  = 0x2F;    //  [
const uint8_t KC_BSPC  = 0x2A;    //  BackSpace
const uint8_t KC_CLCK  = 0x00;    //  CapsLock
const uint8_t KC_CLN   = 0x00;    //  :
const uint8_t KC_SCLN  = 0x00;    //  ;
const uint8_t KC_RSQB  = 0x30;    //  ]
const uint8_t KC_ENTR  = 0x28;    //  Enter
const uint8_t KC_LSFT  = 0x00;    //  Left Shift
const uint8_t KC_COMM  = 0x00;    //  ,
const uint8_t KC_PROD  = 0x00;    //  .
const uint8_t KC_SLH   = 0x00;    //  /
const uint8_t KC_bSLH  = 0x00;    //  Backslash
const uint8_t KC_UP    = 0x00;    //  ↑
const uint8_t KC_RSFT  = 0x00;    //  Right Shift
const uint8_t KC_LCRL  = 0x00;    //  Left Ctrl
const uint8_t KC_LGUI  = 0x00;    //  Left GUI
const uint8_t KC_LALT  = 0x00;    //  Left Alt
const uint8_t KC_SPC   = 0x2C;    //  Space
const uint8_t KC_RALT  = 0x00;    //  Right Alt
const uint8_t KC_RCRL  = 0x00;    //  Right Ctrl
const uint8_t KC_LEFT  = 0x00;    //  ←
const uint8_t KC_DOWN  = 0x00;    //  ↓
const uint8_t KC_RGHT  = 0x00;    //  →
const uint8_t KC_      = 0x00;    //  